---
title: "Projet Analyse de données"
author: "Malleret Antoine, Morille Adrien"
date: "2025-04-02"
output:
  html_document: default
  pdf_document: default
  word_document: default
keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#system("git push origin main")
#system("git pull origin main")
```


```{r, echo=FALSE, results='hide', message=FALSE, warning=FALSE}
#library
library(tidyverse)
library(ggplot2)
library(FactoMineR)  # Pour l'ACP

library(cluster) # classification non supervisée

library(dplyr)        # Pour la manipulation des données

library(randomForest) # Pour la classification supervisée
library(DMwR)
library(gbm) # adaboost
library(pROC) # Pour la courbe ROC
library(glmnet) # Pour la régression Lasso
library(MASS) # Pour lda qda



library(factoextra)   # Pour la visualisation
```

```{r child = "Introduction.Rmd"}

```

```{r child = "DataCleanning.Rmd"}

```

```{r child = "Classification_non_supervisée.Rmd"}

```

## Analyse des scores ESG
```{r child = "ACP.Rmd"}

```

```{r child = "AFC.Rmd"}

```

```{r child = "Classification_supervisée.Rmd"}

```

```{r child = "Annex.Rmd"}

```

```{r child = "Exploration.Rmd"}

```